
export interface GoalStep {
  id: string;
  title: string;
  description: string;
  isCompleted: boolean;
  createdAt: number;
  motivation?: string; // A fun fact or motivational quote generated by AI
  suggestedTools?: string[]; // List of tools/resources suggested by AI
}

export type MapStyle = 'classic' | 'midnight' | 'blueprint' | 'forest';

export interface BigGoal {
  id: string;
  title: string;
  description: string;
  steps: GoalStep[];
  status: 'active' | 'completed' | 'archived';
  createdAt: number;
  themeGradient: string; // CSS linear-gradient string
  mapStyle: MapStyle; // Still used for grid overlays/text contrast logic
  backgroundImage?: string; // Base64 string for AI generated background
}
